//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teference.Shopify.Api {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Teference.Shopify.Api.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccessTokenUrl {
            get {
                return ResourceManager.GetString("AccessTokenUrl", resourceCulture);
            }
        }
        
        internal static string ApiKeyNotFoundException {
            get {
                return ResourceManager.GetString("ApiKeyNotFoundException", resourceCulture);
            }
        }
        
        internal static string AuthorizationUrl {
            get {
                return ResourceManager.GetString("AuthorizationUrl", resourceCulture);
            }
        }
        
        internal static string ClientIdKeyword {
            get {
                return ResourceManager.GetString("ClientIdKeyword", resourceCulture);
            }
        }
        
        internal static string ClientSecretKeyword {
            get {
                return ResourceManager.GetString("ClientSecretKeyword", resourceCulture);
            }
        }
        
        internal static string CodeKeyword {
            get {
                return ResourceManager.GetString("CodeKeyword", resourceCulture);
            }
        }
        
        internal static string DefaultHttpClientContentType {
            get {
                return ResourceManager.GetString("DefaultHttpClientContentType", resourceCulture);
            }
        }
        
        internal static string HmacKeyword {
            get {
                return ResourceManager.GetString("HmacKeyword", resourceCulture);
            }
        }
        
        internal static string KeyShopifyApiKey {
            get {
                return ResourceManager.GetString("KeyShopifyApiKey", resourceCulture);
            }
        }
        
        internal static string KeyShopifyAppSecret {
            get {
                return ResourceManager.GetString("KeyShopifyAppSecret", resourceCulture);
            }
        }
        
        internal static string MyShopifyDomain {
            get {
                return ResourceManager.GetString("MyShopifyDomain", resourceCulture);
            }
        }
        
        internal static string SecretKeyNotFoundException {
            get {
                return ResourceManager.GetString("SecretKeyNotFoundException", resourceCulture);
            }
        }
        
        internal static string ShopKeyword {
            get {
                return ResourceManager.GetString("ShopKeyword", resourceCulture);
            }
        }
        
        internal static string ShopNameNotFoundException {
            get {
                return ResourceManager.GetString("ShopNameNotFoundException", resourceCulture);
            }
        }
        
        internal static string TimestampKeyword {
            get {
                return ResourceManager.GetString("TimestampKeyword", resourceCulture);
            }
        }
        
        internal static string HostKeyword {
            get {
                return ResourceManager.GetString("HostKeyword", resourceCulture);
            }
        }
    }
}
